# -*- coding: utf-8 -*-
"""baseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wUrSYs27tohLB8n6d_r0plOYHFah3eou

A good Baseline
"""

import numpy as np

def persistence_baseline(X_test):
    # Predict last value of the window
    return X_test[:, -1]

