# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z_u6qulImVfiuF4Pg1IybUWVuzpxctq2

(Preprocessing + Windowing)
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

class StockDataset:
    def __init__(self, csv_path, seq_len=60, target_col="Close"):
        self.seq_len = seq_len
        self.target_col = target_col
        self.df = pd.read_csv(csv_path, parse_dates=["Date"])
        self.df = self.df.sort_values("Date").reset_index(drop=True)

    def basic_clean(self):
        # Keep business days only
        self.df = self.df.set_index("Date").asfreq("B")
        self.df = self.df.ffill()
        self.df = self.df.reset_index()

    def scale(self):
        self.scaler = StandardScaler()
        self.df[self.target_col] = self.scaler.fit_transform(
            self.df[self.target_col].values.reshape(-1, 1)
        )

    def make_windows(self):
        X, y = [], []
        vals = self.df[self.target_col].values

        for i in range(len(vals) - self.seq_len):
            X.append(vals[i:i+self.seq_len])
            y.append(vals[i+self.seq_len])

        X = np.array(X).astype(np.float32)
        y = np.array(y).astype(np.float32)
        return X, y

