# -*- coding: utf-8 -*-
"""Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZM3fXBf2rX8ahPRPdhwYhuBwJuvE9gT
"""

import jax
import jax.numpy as jnp
import optax
import numpy as np
from flax.training import train_state

from src.model import TimeSeriesTransformer

def create_train_state(rng, learning_rate, seq_len):
    model = TimeSeriesTransformer(seq_len=seq_len)
    params = model.init(rng, jnp.ones((1, seq_len)))["params"]

    tx = optax.adamw(learning_rate)
    return train_state.TrainState(apply_fn=model.apply, params=params, tx=tx)


def loss_fn(params, batch, state):
    preds = state.apply_fn({"params": params}, batch["X"])
    loss = jnp.mean((preds - batch["y"]) ** 2)
    return loss


@jax.jit
def train_step(state, batch):
    grads = jax.grad(loss_fn)(state.params, batch, state)
    state = state.apply_gradients(grads=grads)
    return state

